@startuml

    abstract class BaseMenu [[../sg/edu/ntu/scse/cz2002/ui/BaseMenu.html]] {
        {static} -PRINT_WINDOW_MAX_SIZE: int
        +startMainMenu(): boolean
        {static} #printHeader(headerName:String): void
        {static} #printHeader(headerName:String, length:int): void
        {static} #printBreaks(length:int): void
        {static} #printBreaks(): void
        {static} #doMenuChoice(max:int, specialEscape:int): int
        {abstract} #generateMenuScreen(): int
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
