@startuml

    class CheckoutMenuUI [[../sg/edu/ntu/scse/cz2002/ui/CheckoutMenuUI.html]] {
        {static} -RECEIPT_SUBFOLDER: String
        #generateMenuScreen(): int
        -checkout(): boolean
        -reprint(): void
        -generateReceipt(o:Order, total:double, paid:double, type:Invoice.PaymentType): ArrayList<String>
        -centerText(toCenter:String, length:int, spacer:char): String
        -spacer(length:int, spacer:char): String
        -requestCashPayment(total:double): double
        -writeReceipt(receipt:ArrayList<String>, receiptId:int): boolean
        -printOrderDetails(o:Order): double
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
