@startuml

    class PromotionMenuUI [[../sg/edu/ntu/scse/cz2002/ui/PromotionMenuUI.html]] {
        ~sc: Scanner
        #generateMenuScreen(): int
        +printPromotion(): void
        +addNewPromotion(newPromoName:String, newPromoPrice:double, newPromoMain:int, newPromoDessert:int, newPromoDrink:int): void
        +editPromotion(targetPromoID:int, editPromoName:String, editPromoPrice:double, editPromoMain:int, editPromoDessert:int, editPromoDrink:int): void
        +deletePromotion(targetPromoID:int): void
        {static} +retrievePromotion(targetPromoID:int): Promotion
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
