@startuml

    class ReservationMenuUI [[../sg/edu/ntu/scse/cz2002/ui/ReservationMenuUI.html]] {
        -input: Scanner
        -MAX_TABLES: int
        #generateMenuScreen(): int
        -createReservationBooking(): void
        -findTableForReservation(numPax:int, resvDate:LocalDate, resvSession:char): int
        -checkReservationBooking(): void
        -removeReservationBooking(): void
        -checkExpiredReservations(): void
        -listReservations(): void
        -printReservationLine(r:Reservation): void
        -printReservationLine(telNo:String): int
        -checkMorningSessionDate(date:LocalDate, isToday:boolean): boolean
        -checkEveningSessionDate(date:LocalDate, isToday:boolean): boolean
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
