@startuml

    class StaffMgmtMenuUI [[../sg/edu/ntu/scse/cz2002/ui/StaffMgmtMenuUI.html]] {
        #generateMenuScreen(): int
        -createNewStaff(): void
        -editStaffInfo(): void
        -removeStaff(): void
        -listAllStaff(): void
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
