@startuml

    class CSVBaseHelper [[../sg/edu/ntu/scse/cz2002/util/CSVBaseHelper.html]] {
        #readAll(reader:BufferedReader, skip:int): List<String[]>
        #writeToCsvFile(writeStrings:List<String[]>, writer:BufferedWriter): void
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
