@startuml

    class DateTimeFormatHelper {
        {static} +formatToStringDate(LocalDate): String
        {static} +formatToStringTime(LocalTime): String
        {static} +formatToLocalDate(String): LocalDate
        {static} +formatToLocalTime(String): LocalTime
        {static} +getTodayDate(boolean): LocalDate
        {static} +getTimeNow(): LocalTime
        {static} +getTimeDifferenceMinutes(LocalTime, LocalTime): long
        {static} +compareIfBeforeToday(LocalDate): boolean
        {static} +formatMillisToDateTime(long): String
        {static} +checkResvTimeSession(LocalTime, LocalTime, LocalTime): boolean
        {static} +validateDate(String): boolean
        {static} +getSysTimeMillisWithSGTimeZone(): long
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
