@startuml

    class DateTimeFormatHelper [[../sg/edu/ntu/scse/cz2002/util/DateTimeFormatHelper.html]] {
        {static} -MILLIS_TO_DAYS: long
        {static} -TO_UTC_PLUS_8: long
        {static} +formatToStringDate(date:LocalDate): String
        {static} +formatToStringTime(time:LocalTime): String
        {static} +formatToLocalDate(date:String): LocalDate
        {static} +formatToLocalTime(time:String): LocalTime
        {static} +getTodayDate(getNextMonth:boolean): LocalDate
        {static} +getTimeNow(): LocalTime
        {static} +getTimeDifferenceMinutes(time1:LocalTime, time2:LocalTime): long
        {static} +compareIfBeforeToday(inputDate:LocalDate): boolean
        {static} +formatMillisToDateTime(millis:long): String
        {static} +checkResvTimeSession(resvTime:LocalTime, sessionStart:LocalTime, sessionEnd:LocalTime): boolean
        {static} + --formatToStringTodayDateTime-- (): String
        {static} +validateDate(date:String): boolean
        {static} +getSysTimeMillisWithSGTimeZone(): long
        {static} + --validateDate-- (d:int, m:int, y:int): boolean
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
