@startuml

    class FileIOHelper [[../sg/edu/ntu/scse/cz2002/util/FileIOHelper.html]] {
        {static} -init(): File
        {static} +exists(name:String): boolean
        {static} +getFile(name:String): File
        {static} +getFileBufferedReader(name:String): BufferedReader
        {static} +getFileBufferedWriter(name:String): BufferedWriter
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
