@startuml

    class MenuItemCSVHelper [[../sg/edu/ntu/scse/cz2002/util/MenuItemCSVHelper.html]] {
        {static} -mInstance: MenuItemCSVHelper
        -menuItemCsv: String
        {static} +getInstance(): MenuItemCSVHelper
        +readFromCsv(): ArrayList<MenuItem>
        +writeToCsv(items:ArrayList<MenuItem>): void
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
