@startuml

    class OrderCSVHelper [[../sg/edu/ntu/scse/cz2002/util/OrderCSVHelper.html]] {
        {static} -mInstance: OrderCSVHelper
        -orderCsv: String
        -OrderCSVHelper()
        + --OrderCSVHelper-- (filename:String)
        {static} +getInstance(): OrderCSVHelper
        +readFromCsv(): ArrayList<Order>
        +writeToCsv(items:ArrayList<Order>): void
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
