@startuml

    class PromoCSVHelper [[../sg/edu/ntu/scse/cz2002/util/PromoCSVHelper.html]] {
        {static} -pInstance: PromoCSVHelper
        -promotionCsv: String
        {static} +getInstance(): PromoCSVHelper
        +readFromCsv(): ArrayList<Promotion>
        +writeToCsv(promotions:ArrayList<Promotion>): void
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
