@startuml

    class ScannerHelper [[../sg/edu/ntu/scse/cz2002/util/ScannerHelper.html]] {
        {static} +instance: Scanner
        {static} +getIntegerInput(prompt:String): int
        {static} +getIntegerInput(prompt:String, min:int): int
        {static} +getIntegerInput(prompt:String, min:int, max:int): int
        {static} +getYesNoInput(prompt:String): boolean
        {static} +getScannerInput(): Scanner
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
