@startuml

    class ScannerHelper {
        {static} +instance: Scanner
        {static} +getIntegerInput(String): int
        {static} +getIntegerInput(String, int): int
        {static} +getIntegerInput(String, int, int): int
        {static} +getYesNoInput(String): boolean
        {static} +getScannerInput(): Scanner
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
