@startuml

    class TableCSVHelper [[../sg/edu/ntu/scse/cz2002/util/TableCSVHelper.html]] {
        {static} -mInstance: TableCSVHelper
        -tableCsv: String
        -TableCSVHelper()
        + --TableCSVHelper-- (filename:String)
        {static} +getInstance(): TableCSVHelper
        +readFromCsv(): ArrayList<Table>
        + --writeToCsv-- (tables:ArrayList<Table>): void
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
