@startuml

    namespace sg.edu.ntu.scse.cz2002.objects.menuitem {

        class MenuItem [[../sg/edu/ntu/scse/cz2002/objects/menuitem/MenuItem.html]] {
            #id: int
            #name: String
            #type: String
            #description: String
            #price: double
            +MenuItem()
            +MenuItem(id:int, name:String, type:String, description:String, price:double)
            +MenuItem(csv:String[])
            +toCsv(): String[]
            +getId(): int
            +setId(id:int): void
            +getName(): String
            +setName(name:String): void
            +getType(): String
            +setType(type:String): void
            +getDescription(): String
            +setDescription(description:String): void
            +getPrice(): double
            +setPrice(price:double): void
            +printItemDetail(): String
        }

        class ItemNotFoundException [[../sg/edu/ntu/scse/cz2002/objects/menuitem/ItemNotFoundException.html]] {
            +ItemNotFoundException(message:String)
        }

        class Promotion [[../sg/edu/ntu/scse/cz2002/objects/menuitem/Promotion.html]] {
            #promoID: int
            #promoName: String
            #promoPrice: double
            #promoMain: int
            #promoDessert: int
            #promoDrink: int
            +Promotion()
            +Promotion(promoID:int, promoName:String, promoPrice:double, promoMain:int, promoDessert:int, promoDrink:int)
            +Promotion(csv:String[])
            +toCsv(): String[]
            +getPromoID(): int
            +setPromoID(promoID:int): void
            +getPromoName(): String
            +setPromoName(promoName:String): void
            +getPromoPrice(): double
            +setPromoPrice(promoPrice:double): void
            +getPromoMain(): int
            +setPromoMain(promoMain:int): void
            +getPromoDessert(): int
            +setPromoDessert(promoDessert:int): void
            +getPromoDrink(): int
            +setPromoDrink(promoDrink:int): void
            +printPromotionDetail(): String
        }

        interface sg.edu.ntu.scse.cz2002.util.ICsvSerializable {
            {abstract} +toCsv(): String[]
        }
        sg.edu.ntu.scse.cz2002.util.ICsvSerializable <|.. MenuItem

        class java.lang.Exception
        java.lang.Exception <|-- ItemNotFoundException

        sg.edu.ntu.scse.cz2002.util.ICsvSerializable <|.. Promotion

    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
