@startuml

    namespace sg.edu.ntu.scse.cz2002.objects.menuitem {

        class MenuItem {
            #id: int
            #name: String
            #type: String
            #description: String
            #price: double
            +MenuItem()
            +MenuItem(int, String, String, String, double)
            +MenuItem(String[])
            +toCsv(): String[]
            +getId(): int
            +setId(int): void
            +getName(): String
            +setName(String): void
            +getType(): String
            +setType(String): void
            +getDescription(): String
            +setDescription(String): void
            +getPrice(): double
            +setPrice(double): void
        }

        class ItemNotFoundException {
            +ItemNotFoundException(String)
        }

        class Promotion {
            #promoID: int
            #promoName: String
            #promoPrice: double
            #promoMain: int
            #promoDessert: int
            #promoDrink: int
            +Promotion()
            +Promotion(int, String, double, int, int, int)
            +Promotion(String[])
            +toCsv(): String[]
            +getPromoID(): int
            +setPromoID(int): void
            +getPromoName(): String
            +setPromoName(String): void
            +getPromoPrice(): double
            +setPromoPrice(double): void
            +getPromoMain(): int
            +setPromoMain(int): void
            +getPromoDessert(): int
            +setPromoDessert(int): void
            +getPromoDrink(): int
            +setPromoDrink(int): void
        }

        interface sg.edu.ntu.scse.cz2002.util.ICsvSerializable {
            {abstract} +toCsv(): String[]
        }
        sg.edu.ntu.scse.cz2002.util.ICsvSerializable <|.. MenuItem

        class java.lang.Exception
        java.lang.Exception <|-- ItemNotFoundException

        sg.edu.ntu.scse.cz2002.util.ICsvSerializable <|.. Promotion

    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
