@startuml

    namespace sg.edu.ntu.scse.cz2002 {

        class MainApp [[../sg/edu/ntu/scse/cz2002/MainApp.html]] {
            {static} +APP_NAME: String
            {static} +tables: ArrayList<Table>
            {static} +menuItems: ArrayList<MenuItem>
            {static} +invoices: ArrayList<Invoice>
            {static} +reservations: ArrayList<Reservation>
            {static} +promotions: ArrayList<Promotion>
            {static} +staffs: ArrayList<Staff>
            {static} +restaurantSession: char
            {static} +DEBUG: boolean
            {static} -init(): void
            {static} +saveAll(): boolean
            {static} +main(args:String[]): void
            {static} -printWelcomeAscii(): void
            {static} -checkTodayReservations(): int
        }

    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
