@startuml

    class OrderItem [[../sg/edu/ntu/scse/cz2002/features/OrderItem.html]] {
        -itemId: int
        -quantity: int
        -itemTotal: double
        -itemType: OrderItem.OrderItemType
        +OrderItem(otherData:String[])
        +OrderItem(itemId:int, quantity:int, itemType:OrderItem.OrderItemType)
        +toCompiledString(): String
        -getPromo(): Promotion
        -getMenuItem(): MenuItem
        +getItem(): Object
        +getItemName(): String
        +getItemId(): int
        +getQuantity(): int
        +setQuantity(quantity:int): void
        +isPromotion(): boolean
        +getItemTotal(): double
        +calculateTotal(): void
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
