@startuml

    enum OrderItem.OrderItemType [[../sg/edu/ntu/scse/cz2002/features/OrderItem.OrderItemType.html]] {
        {static} +TYPE_MENU
        {static} +TYPE_PROMO
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
