@startuml

    class Order [[../sg/edu/ntu/scse/cz2002/features/Order.html]] {
        -orderID: int
        -orderItems: ArrayList<OrderItem>
        -subtotal: double
        -orderState: Order.OrderState
        -createdAt: long
        -completedAt: long
        -staffId: int
        -tableId: int
        +Order(orderID:int)
        #Order(o:Order)
        +Order(csv:String[])
        +toCsv(): String[]
        +getOrderID(): int
        +getOrderItems(): ArrayList<OrderItem>
        +setOrderItems(orderItems:ArrayList<OrderItem>): void
        +getSubtotal(): double
        +calculateSubtotal(): void
        +getOrderState(): Order.OrderState
        +markPaid(): void
        +getCreatedAt(): long
        +getCompletedAt(): long
        +getStaffId(): int
        +setStaffId(staff:int): void
        +getTableId(): int
        +setTableId(table:int): void
        +getStaff(): Staff
        +getTable(): Table
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
