@startuml

    class Reservation [[../sg/edu/ntu/scse/cz2002/features/Reservation.html]] {
        -resvId: int
        -resvDate: LocalDate
        -resvTime: LocalTime
        -resvSession: Reservation.ReservationSession
        -custTelNo: String
        -custName: String
        -numPax: int
        -tableNum: int
        +Reservation(id:int, rd:LocalDate, rt:LocalTime, sess:char, telNo:String, name:String, pax:int, t:int)
        +Reservation(csv:String[])
        +toCsv(): String[]
        +getResvId(): int
        +setResvId(resvId:int): void
        +getResvDate(): LocalDate
        +setResvDate(resvDate:LocalDate): void
        +getResvTime(): LocalTime
        +setResvTime(resvTime:LocalTime): void
        +getResvSession(): Reservation.ReservationSession
        +setResvSession(resvSession:Reservation.ReservationSession): void
        +getNumPax(): int
        +setNumPax(numPax:int): void
        +getCustName(): String
        +setCustName(custName:String): void
        +getCustTelNo(): String
        +setCustTelNo(custTelNo:String): void
        +getTableNum(): int
        +setTableNum(tableNum:int): void
        {static} +hasReservation(telNo:String): Table
        {static} +getTablesBookedOnDateBySession(resvDate:LocalDate, resvSession:char): ArrayList<Table>
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
