@startuml

    enum Table.TableSeats [[../sg/edu/ntu/scse/cz2002/features/Table.TableSeats.html]] {
        {static} +TWO_SEATER
        {static} +FOUR_SEATER
        {static} +EIGHT_SEATER
        {static} +TEN_SEATER
        {static} +UNKNOWN_SEATER
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
