@startuml

    class Staff [[../sg/edu/ntu/scse/cz2002/objects/person/Staff.html]] {
        -staffId: int
        -staffName: String
        -gender: char
        -jobTitle: String
        +Staff(id:int, name:String, gender:char, title:String)
        +Staff(csv:String[])
        +toCsv(): String[]
        +getStaffId(): int
        +getStaffName(): String
        +setStaffName(staffName:String): void
        +getGender(): char
        +setGender(gender:char): void
        +getJobTitle(): String
        +setJobTitle(jobTitle:String): void
        {static} +getStaff(staffId:int): Staff
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
