@startuml

    class Staff {
        +Staff(int, String, char, String)
        +Staff(String[])
        +toCsv(): String[]
        +getStaffId(): int
        +getStaffName(): String
        +setStaffName(String): void
        +getGender(): char
        +setGender(char): void
        +getJobTitle(): String
        +setJobTitle(String): void
        {static} +getStaff(int): Staff
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
