@startuml

    enum MenuItem.MenuItemType [[../sg/edu/ntu/scse/cz2002/objects/restaurantItem/MenuItem.MenuItemType.html]] {
        {static} +ALL
        {static} +MAIN
        {static} +DESSERT
        {static} +DRINK
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
