@startuml

    class MenuItem [[../sg/edu/ntu/scse/cz2002/objects/restaurantItem/MenuItem.html]] {
        -eType: MenuItem.MenuItemType
        #description: String
        +MenuItem(id:int, name:String, type:int, description:String, price:double)
        +MenuItem(csv:String[])
        +toCsv(): String[]
        +getType(): MenuItem.MenuItemType
        +setType(type:int): void
        +getDescription(): String
        +setDescription(description:String): void
        +convertToItemType(type:int): MenuItem.MenuItemType
        +printItemDetail(): String
        {static} +menuTypeChecker(menuArrayList:ArrayList<MenuItem>, newPromoItemType:int, textParameter:String): boolean
        {static} +retrieveMenuItem(targetItemID:int): MenuItem
        {static} +retrieveMenuItemListFiltered(targetItemType:MenuItem.MenuItemType): ArrayList<MenuItem>
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
