@startuml

    class RestaurantItem [[../sg/edu/ntu/scse/cz2002/objects/restaurantItem/RestaurantItem.html]] {
        -restaurantItemID: int
        -restaurantItemName: String
        -restaurantItemPrice: double
        ~RestaurantItem(restaurantItemID:int, restaurantItemName:String, restaurantItemPrice:double)
        ~RestaurantItem(csv:String[])
        +toCsv(): String[]
        +getId(): int
        +setId(restaurantItemID:int): void
        +getName(): String
        +setName(restaurantItemName:String): void
        +getPrice(): double
        +setPrice(restaurantItemPrice:double): void
    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
