@startuml

    namespace sg.edu.ntu.scse.cz2002 {

        class MainApp [[../sg/edu/ntu/scse/cz2002/MainApp.html]] {
            {static} +tables: ArrayList<String>
            {static} +menuItems: ArrayList<String>
            {static} +completedOrders: ArrayList<String>
            {static} +reservations: ArrayList<String>
            {static} +promotions: ArrayList<String>
            {static} +staffs: ArrayList<String>
            {static} +restaurantSession: char
            {static} -DEBUG: boolean
            {static} -init(): void
            {static} +saveAll(): boolean
            {static} +main(args:String[]): void
            {static} -printWelcomeAscii(): void
            {static} -checkTodayReservations(): int
        }

    }


    center footer UMLDoclet 1.1.3, PlantUML 1.2018.12
@enduml
